version: '3.9'
services:
  postgres:
    image: postgres:15.2-bullseye
    container_name: postgres
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
  web:
    image: golang:1.20-bullseye
    container_name: web
    volumes:
      - ./web:/work/web
    working_dir: /work/web
    tty: true